<?php
/**
 * @file
 * Code for the MRSS Feed Importer feature.
 */

include_once 'ik_mrss_feed_importer.features.inc';

/**
 * Defines a new feeds parser to Yahoo Search Media RSS feeds. You can read
 * about the format at http://en.wikipedia.org/wiki/Media_RSS.
 *
 * @return array $info
 */
function ik_mrss_feed_importer_feeds_plugins() {
  return array(
    'MediaRSS' => array(
      'name' => "Media RSS",
      'description' => t('Parse Yahoo Media RSS feed'),
      'handler' => array(
        'parent' => 'FeedsParser',
        'class' => 'MediaRSSParser',
        'file' => 'mrss.class.inc',
        'path' => drupal_get_path('module', 'ik_mrss_feed_importer' ) . '/includes',
      ),
    ),
  );
}

/**
 * Make sure that the feed parser cache is cleared on module activation.
 */
function ik_mrss_feed_importer_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}

/**
 * Alter mapping targets for entities. In this case alter target for jQuery
 * colorpicker fields on slide nodes.
 *
 * @param &$targets
 *   Array containing the targets to be offered to the user. Add to this array
 *   to expose additional options. Remove from this array to suppress options.
 *   Remove with caution.
 * @param $entity_type
 *   The entity type of the target, for instance a 'node' entity.
 * @param $bundle_name
 *   The bundle name for which to alter targets.
 */
function ik_mrss_feed_importer_feeds_processor_targets_alter(&$targets, $entity_type, $bundle_name) {
  if ($entity_type == 'node' && $bundle_name == 'slide') {
    $targets['field_ik_slide_text_color'] = array(
      'name' => t('Text Color'),
      'description' => t('Set slide text color.'),
      'callback' => 'ik_mrss_feed_importer_color_set_target',
    );
    $targets['field_ik_slide_color'] = array(
      'name' => t('Color'),
      'description' => t('Set slide color.'),
      'callback' => 'ik_mrss_feed_importer_color_set_target',
    );

    // Change OG node field tagets
    $targets['field_ik_og_department_ref']['callback'] = 'ik_mrss_feed_importer_og_set_target';
  }
}

/**
 * Save OG values for feeds taget mapping as they conflict with feeds own ref
 * fields.
 *
 * @param $source
 *   Field mapper source settings.
 * @param $entity
 *   An entity object, for instance a node object.
 * @param $target
 *   A string identifying the target on the node.
 * @param $value
 *   The value to populate the target with.
 * @param $mapping
 *  Associative array of the mapping settings from the per mapping
 *  configuration form.
 */
function ik_mrss_feed_importer_color_set_target($source, $entity, $target, $value, $mapping) {
  $entity->{$target}[$entity->language][0]['jquery_colorpicker'] = $value;
}

/**
 * Save jQuery color picker value for feeds taget mapping.
 *
 * @param $source
 *   Field mapper source settings.
 * @param $entity
 *   An entity object, for instance a node object.
 * @param $target
 *   A string identifying the target on the node.
 * @param $value
 *   The value to populate the target with.
 * @param $mapping
 *  Associative array of the mapping settings from the per mapping
 *  configuration form.
 */
function ik_mrss_feed_importer_og_set_target($source, $entity, $target, $value, $mapping) {
  $entity->{$target}[$entity->language][0]['target_id'] = $value;
}