<?php

/**
 * Implements hook_form_alter().
 *
 * Remove the -none- option from OG group reference field on slide add form.
 */
function ik_admin_form_alter(&$form, &$form_state, $form_id) {
  // OG department reference alter.
  $forms_to_alter = array('channel_node_form' , 'slide_node_form' , 'media_rss_slide_import_node_form');
  if (in_array($form['form_id']['#value'] , $forms_to_alter)) {
    $language = $form['field_ik_og_department_ref']['#language'];
    if (isset($form['field_ik_og_department_ref'][$language][0]['default']['#options'])) {
      unset($form['field_ik_og_department_ref'][$language][0]['default']['#options']['_none']);
    }

    // Hide flags fieldset and imported fieldset when user is not 1
    global $user;
    if ($user->uid > 1) {
      $form['flag']['#access'] = FALSE;
      $form['#fieldgroups']['group_ik_slide_import']->access = FALSE;
      $form['field_ik_slide_import_node']['#access'] = FALSE;
      $form['field_ik_slide_imported']['#access'] = FALSE;
    }
  }

  // Manipulate the media upload form.
  if ($form['form_id']['#value'] == 'file_entity_add_upload') {

    // Hide root folder.
    unset($form['field_folder']['#options'][83]);

    // Set the media plus browser folders to logoer.
    if (stristr($form['upload']['#upload_location'], 'slide_logo_files')) {
      $form['field_folder']['#default_value'] = 30;
    }
  }
}

/**
 * Implements hook_init().
 *
 * This is not optimal, but we have no idea when the code is needed.
 */
function ik_admin_init() {
  // We set at high weight to ensure that this overrides the JS from the media
  // module.
  drupal_add_js(drupal_get_path('module', 'ik_admin') . '/js/ik_admin.js', array(
    'scope' => 'footer',
    'weight' => '20',
  ));
}

/**
 * Implements hook_pathauto_alias_alter().
 */
function ik_admin_pathauto_alias_alter(&$alias, array &$context) {
  // Force all aliases to be saved as language neutral.
  $context['language'] = LANGUAGE_NONE;
}
