<?php

/**
 * Implements hook_form_alter().
 *
 * Remove the -none- option from OG group reference field on slide add form.
 */
function ik_admin_form_alter(&$form, &$form_state, $form_id) {
  
  // OG department reference alter.
  $forms_to_alter = array('channel_node_form' , 'slide_node_form' , 'media_rss_slide_import_node_form' );
  if ( in_array( $form['form_id']['#value'] , $forms_to_alter ) ) {
    $language = $form['field_ik_og_department_ref']['#language'];
    if (isset($form['field_ik_og_department_ref'][$language][0]['default']['#options'])) {
      unset($form['field_ik_og_department_ref'][$language][0]['default']['#options']['_none']);  
    }
  }

  // Manipulate the media upload form.
  if ( $form['form_id']['#value'] == 'file_entity_add_upload' ) {
    if ( stristr($form['upload']['#upload_location'], 'slide_logo_files') ) {
      kpr($form);
    }
  }
}

/**
 * Implements hook_pathauto_alias_alter().
 */
function ik_admin_pathauto_alias_alter(&$alias, array &$context) {
  // Force all aliases to be saved as language neutral.
  $context['language'] = LANGUAGE_NONE;
}