<?php

/**
 * @file
 *
 */

/**
 * Implements hook_field_info().
 *
 * Search field.
 */
function ik_filter_field_info() {
  return array(
    'itk_filter_search' => array(
      'label' => t(''),
      'description' => t(''),
      'default_widget' => 'itk_filter_search_widget',
      'default_formatter' => 'itk_filter_search_formatter',
    ),
  );
}


/**
 * Implements hook_field_widget_info().
 *
 */
function ik_filter_field_widget_info() {
  return array(
    'itk_filter_search_widget' => array(
      'label' => t(''),
      'field types' => array('itk_filter_search'),
    ),
    'itk_filter_search_autocomplete' => array(
      'label' => t(''),
      'field types' => array('itk_filter_search'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 *
 */
function ik_filter_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $element += array(
    '#type' => 'fieldset',
  );
}

/**
 * Implements hook_field_is_empty().
 *
 */
function ik_filter_field_is_empty($item, $field) {

}

/**
 * Implements hook_field_validate().
 *
 */
function ik_filter_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {

}

/**
 * Implements hook_field_widget_error().
 *
 */
function ik_filter_field_widget_error($element, $error, $form, &$form_state) {

}

/**
 * Implements hook_field_formatter_info().
 *
 */
function ik_filter_field_formatter_info() {
  return array(
    'itk_filter_search_formatter' => array(
      'label' => t(''),
      'field types' => array('itk_filter_search'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 */
function ik_filter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

}