<?php
/**
 * @file
 *
 */

/**
 * Implements hook_menu().
 */
function ik_frontend_menu() {
  $items = array();

  $items['channels/%/run'] = array(
    'title' => 'Start slideshow channel',
    'page callback' => 'ik_frontend_run',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['channels/%/update'] = array(
    'title' => 'Request updated slide information',
    'page callback' => 'ik_frontend_update',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['channels/%/slide/%'] = array(
    'title' => 'Request slide information',
    'page callback' => 'ik_frontend_fetch_slide',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ik_frontend_theme() {
  return array(
    'ik_frontend_buttons' => array(
      'variables' => array('title' => NULL, 'buttons' => NULL),
      'template' => 'templates/ik-frontend-buttons',
      'file' => 'ik_frontend.theme.inc',
    ),
    'ik_frontend' => array(
      'varibles' => array('token' => NULL),
      'template' => 'templates/ik-frontend',
      'file' => 'ik_frontend.theme.inc',
    ),
  );
}

/**
 * Implements hook_flush_caches().
 */
function ik_frontend_flush_caches() {
  return array('cache_ik_frontend');
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function ik_frontend_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_node_insert().
 *
 * It's a funny place to have the node hook, but we need this mapping in the
 * front end to fast fetch channels.
 */
function ik_frontend_node_insert($node) {
  if ($node->type == 'channel') {
    $token = ik_channel_filter_token($node->nid);
    $record = array('nid' => $node->nid, 'token' => $token);
    drupal_write_record('ik_channel_mapping', $record);
  }
}

/**
 * Implements hook_node_delete().
 *
 * Make sure that we remove old channel tokens.
 */
function ik_frontend_node_delete($node) {
  if ($node->type == 'channel') {
    db_delete('ik_channel_mapping')->condition('nid', $node->nid)->execute();
  }
}

/**
 * Implements hook_node_update().
 */
function ik_frontend_node_update($node) {
  if ($node->type == 'channel') {
    // Remove node for channel cache.
    $token = ik_channel_filter_token($node->nid);
    cache_clear_all('channel_' . $token, 'cache_ik_frontend');
  }
  if ($node->type == 'slide') {
    // Remove node from slides cache.
//    cache_clear_all('slide_' . $node->nid, 'cache_ik_frontend');
  }
}

/**
 * Get channel nid based on channel token mapping.
 *
 * @param string $token
 *   Token representing a given channel.
 *
 * @return int
 *   Channel node id.
 */
function ik_frontend_find_channel_nid($token) {
  $nid = db_select('ik_channel_mapping', 'ikcm')
    ->fields('ikcm', array('nid'))
    ->condition('token', $token)
    ->execute()
    ->fetchCol();
  return $nid[0];
}

/**
 * Helper function that fetches basic information about a channels slides based
 * on the channels filter selections.
 *
 * @param string $token
 *   Token sting to identify the channel.
 * @param Object $entity
 *   Channel entity to used to filter the slides.
 *
 * @return array
 *   Array of slides with nid and title for each.
 */
function ik_frontend_get_slides($token, $entity) {
  $slides = array();

  // Use frontend cache, if available.
  if ($cache = cache_get('channel_' . $token, 'cache_ik_frontend')) {
    if ($cache->expire > REQUEST_TIME) {
      $slides = $cache->data;
    }
  }

  // Either the cache was cold or expired, so we need to generate new slides.
  if (empty($slides)) {
    $field = field_info_field('field_channel_preview');
    $field_names = isset($field['settings']['ik_search']['types']) ? $field['settings']['ik_search']['types'] : array();
    $values = array();
    foreach ($field_names as $fieldname) {
      $field = $entity->$fieldname;
      if (!empty($field)) {
        foreach ($field as $lang => $data) {
          $values[$fieldname] = $data[0]['data'];
        }
      }
    }

    // Get basic slide information based on the filter.
    module_load_include('inc', 'ik_channel_filter', 'ik_channel_filter.queries');
    $slides = ik_channel_filter_get_slides($values);

    // Save the content in the cache (removed on node update).
    cache_set('channel_' . $token, $slides, 'cache_ik_frontend', REQUEST_TIME + 600);
  }

  return $slides;
}

/**
 * Menu callback that returns the basic slide show page. The starting point of
 * the frontend JS.
 *
 * @param string $token
 *   Channel token.
 */
function ik_frontend_run($token) {
  // Return skeleton for slide show (complet HTML page <header><content><footer>
  // etc.).
  echo theme('ik_frontend', array(
    'settings' => array(
      'token' => $token,
    ),
    'start' => TRUE,
  ));
}

/**
 * Builds information about a given channels slids and returns slide ids (node
 * ids) for the channel.
 *
 * @param string $token
 *   Channel token.
 */
function ik_frontend_update($token) {
  // Find filter values, by loading channel node (cache the result).
  $nid = ik_frontend_find_channel_nid($token);
  $entity = node_load($nid);

  // Get values that should be used to find slides.
  $slides = ik_frontend_get_slides($token, $entity);

  // JSON encode.
  drupal_json_output($slides);
}

/**
 * Builds a slide as a JSON object based on slide id and channel token.
 *
 * @param int $sid
 *   Slide id (node id).
 * @param bool $json
 *   Should the function JSON encode the result (defaults to TRUE).
 * @param bool $reset
 *   Reset cache if TRUE. Default FALSE.
 *
 * @return StdClass
 *   Slide class.
 */
function ik_frontend_fetch_slide($sid, $json = TRUE, $reset = FALSE) {
  // Use frontend cache, if available.
  if (!$reset && $cache = cache_get('slide_' . $sid, 'cache_ik_frontend')) {
    $slide = $cache->data;
  }
  else {
    // Load slide node content entity_load().
    $entity = node_load($sid);

    // Build slide with information found on the node.
    $slide = new stdClass();
    $slide->sid = $sid;
    $slide->title = check_plain($entity->title);

    // Color theme for text-box.
    // Default color option is #1
    $slide->color = ik_frontend_select_color_theme('1');
    if ($data = field_get_items('node', $entity, 'field_ik_slide_color_theme')) {
      $slide->color = ik_frontend_select_color_theme($data[0]['value']);
    }

    $slide->fontsize = ik_frontend_select_font_size(0);
    if ($data = field_get_items('node', $entity, 'field_ik_slide_font_size')) {
      $slide->fontsize = ik_frontend_select_font_size($data[0]['value']);
    }

    $slide->logo = '';
    if ($data = field_get_items('node', $entity, 'field_ik_slide_logo')) {
      $slide->logo = image_style_url('slide_logoes', $data[0]['uri']);
    }

    $slide->transition = 'cubeSize';
    if ($data = field_get_items('node', $entity, 'field_ik_slide_transition_effect')) {
      $slide->transition = $data[0]['value'];
    }

    $slide->media = array(
      'image' => array(),
      'video' => array(),
    );
    if ($data = field_get_items('node', $entity, 'field_ik_slide_media')) {
      foreach ($data as $media) {
        $file = file_load($media['fid']);
        $mime = substr($file->filemime, 0, strpos($file->filemime, '/'));
        $url = $file->uri;
        if ($mime == 'image') {
          $url = image_style_url('slide_images', $file->uri);
        }
        $slide->media[$mime][$media['fid']] = $url;
      }
    }

    $slide->subheading = '';
    if ($data = field_get_items('node', $entity, 'field_ik_slide_subheading')) {
      $slide->subheading = $data[0]['safe_value'];
    }

    $slide->text = '';
    if ($data = field_get_items('node', $entity, 'field_ik_slide_text')) {
      $slide->text = $data[0]['safe_value'];
    }

    // Convert exposure to mill sec.
    $slide->exposure = 30000;
    if ($data = field_get_items('node', $entity, 'field_ik_slide_exposure')) {
      $slide->exposure = $data[0]['value'] * 1000;
    }

    // Amount of media on slide, used to calculate interval.
    $slide->mediacount = count($slide->media);

    $slide->layout = 'layout-1';
    if ($data = field_get_items('node', $entity, 'field_layout')) {
      $slide->layout = str_replace('_', '-', $data[0]['value']);
    }

    // Save the content in the cache (updated on node save).
    cache_set('slide_' . $sid, $slide, 'cache_ik_frontend');
  }

  // Return the slide as JSON.
  if ($json) {
    drupal_json_output($slide);
  }
  else {
    return $slide;
  }
}

/**
 * Returns the name of the font size selected.
 *
 * @param int $value
 *   Value from the font size field.
 *
 * @return string
 *   Selected font size.
 */
function ik_frontend_select_font_size($value) {
  switch ($value) {
    case 0:
      $font_size = 'normal';
      break;

    case 1:
      $font_size = 'bigger';
      break;

    default:
      $font_size = 'normal';
  }

  return $font_size;
}

/**
 * Returns an array with color codes for the selected color theme.
 *
 * @param int $value
 *   Value from color theme field.
 *
 * @return string
 *   Color option.
 */
function ik_frontend_select_color_theme($value) {
  switch ($value) {
    case 1:
      $color_theme = 'white-green';
      break;

    case 2:
      $color_theme = 'white-blue';
      break;

    case 3:
      $color_theme = 'white-bordeaux';
      break;

    case 4:
      $color_theme = 'white-grey';
      break;

    case 5:
      $color_theme = 'black-orange';
      break;

    default:
      $color_theme = 'white-green';
  }

  return $color_theme;
}
