<?php
/**
 * @file
 * Code for the IK slides feature.
 */

/**
 * Hook_form_alter()
 * Change the labels on select layout radio buttons.
 */
function ik_slides_form_slide_node_form_alter(&$form, &$form_state, $form_id) {
  $path = drupal_get_path('module', 'ik_slides');
  $form["field_layout"]["und"]["#options"] = array(
    'layout_1' => theme('image', array('path' => $path . '/layout-images/layout_1.png', 'alt' => t('Text to the left'), 'title' => t('Text to the left'))),
    'layout_2' => theme('image', array('path' => $path . '/layout-images/layout_2.png', 'alt' => t('Text in top'), 'title' => t('Text in top'))),
    'layout_3' => theme('image', array('path' => $path . '/layout-images/layout_3.png', 'alt' => t('Text in bottom'), 'title' => t('Text in bottom'))),
    'layout_4' => theme('image', array('path' => $path . '/layout-images/layout_4.png', 'alt' => t('Text to the right'), 'title' => t('Text to the right'))),
    'layout_5' => theme('image', array('path' => $path . '/layout-images/layout_5.png', 'alt' => t('Image only'), 'title' => t('Image only'))),
    'layout_6' => theme('image', array('path' => $path . '/layout-images/layout_6.png', 'alt' => t('Text only'), 'title' => t('Text only'))),
    'layout_7' => theme('image', array('path' => $path . '/layout-images/layout_7.png', 'alt' => t('Feed import (text)'), 'title' => t('Feed import (text)')))
  );

  if (isset($form['field_ik_slide_font_size']["und"]['#options'])) {
    unset($form['field_ik_slide_font_size']["und"]['#options']['_none']);
  }
}

include_once 'ik_slides.features.inc';
